apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime
spec:
  template:
    spec:
      containers:
      - name: datetime
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
